columns = [{"id"=>"FILEID", "type"=>"Text", "len"=>6},
 {"id"=>"STUSAB", "type"=>"Text", "len"=>2},
 {"id"=>"SUMLEV", "type"=>"Text", "len"=>3},
 {"id"=>"GEOCOMP", "type"=>"Text", "len"=>2},
 {"id"=>"CHARITER", "type"=>"Text", "len"=>3},
 {"id"=>"CIFSN", "type"=>"Text", "len"=>2},
 {"id"=>"LOGRECNO", "type"=>"Text", "len"=>7},
 {"id"=>"REGION", "type"=>"Text", "len"=>1},
 {"id"=>"DIVISION", "type"=>"Text", "len"=>1},
 {"id"=>"STATE", "type"=>"Text", "len"=>2},
 {"id"=>"COUNTY", "type"=>"Text", "len"=>3},
 {"id"=>"COUNTYCC", "type"=>"Text", "len"=>2},
 {"id"=>"COUNTYSC", "type"=>"Text", "len"=>2},
 {"id"=>"COUSUB", "type"=>"Text", "len"=>5},
 {"id"=>"COUSUBCC", "type"=>"Text", "len"=>2},
 {"id"=>"COUSUBSC", "type"=>"Text", "len"=>2},
 {"id"=>"PLACE", "type"=>"Text", "len"=>5},
 {"id"=>"PLACECC", "type"=>"Text", "len"=>2},
 {"id"=>"PLACESC", "type"=>"Text", "len"=>2},
 {"id"=>"TRACT", "type"=>"Text", "len"=>6},
 {"id"=>"BLKGRP", "type"=>"Text", "len"=>1},
 {"id"=>"BLOCK", "type"=>"Text", "len"=>4},
 {"id"=>"IUC", "type"=>"Text", "len"=>2},
 {"id"=>"CONCIT", "type"=>"Text", "len"=>5},
 {"id"=>"CONCITCC", "type"=>"Text", "len"=>2},
 {"id"=>"CONCITSC", "type"=>"Text", "len"=>2},
 {"id"=>"AIANHH", "type"=>"Text", "len"=>4},
 {"id"=>"AIANHHFP", "type"=>"Text", "len"=>5},
 {"id"=>"AIANHHCC", "type"=>"Text", "len"=>2},
 {"id"=>"AIHHTLI", "type"=>"Text", "len"=>1},
 {"id"=>"AITSCE", "type"=>"Text", "len"=>3},
 {"id"=>"AITS", "type"=>"Text", "len"=>5},
 {"id"=>"AITSCC", "type"=>"Text", "len"=>2},
 {"id"=>"TTRACT", "type"=>"Text", "len"=>6},
 {"id"=>"TBLKGRP", "type"=>"Text", "len"=>1},
 {"id"=>"ANRC", "type"=>"Text", "len"=>5},
 {"id"=>"ANRCCC", "type"=>"Text", "len"=>2},
 {"id"=>"CBSA", "type"=>"Text", "len"=>5},
 {"id"=>"CBSASC", "type"=>"Text", "len"=>2},
 {"id"=>"METDIV", "type"=>"Text", "len"=>5},
 {"id"=>"CSA", "type"=>"Text", "len"=>3},
 {"id"=>"NECTA", "type"=>"Text", "len"=>5},
 {"id"=>"NECTASC", "type"=>"Text", "len"=>2},
 {"id"=>"NECTADIV", "type"=>"Text", "len"=>5},
 {"id"=>"CNECTA", "type"=>"Text", "len"=>3},
 {"id"=>"CBSAPCI", "type"=>"Text", "len"=>1},
 {"id"=>"NECTAPCI", "type"=>"Text", "len"=>1},
 {"id"=>"UA", "type"=>"Text", "len"=>5},
 {"id"=>"UASC", "type"=>"Text", "len"=>2},
 {"id"=>"UATYPE", "type"=>"Text", "len"=>1},
 {"id"=>"UR", "type"=>"Text", "len"=>1},
 {"id"=>"CD", "type"=>"Text", "len"=>2},
 {"id"=>"SLDU", "type"=>"Text", "len"=>3},
 {"id"=>"SLDL", "type"=>"Text", "len"=>3},
 {"id"=>"VTD", "type"=>"Text", "len"=>6},
 {"id"=>"VTDI", "type"=>"Text", "len"=>1},
 {"id"=>"RESERVE2", "type"=>"Text", "len"=>3},
 {"id"=>"ZCTA5", "type"=>"Text", "len"=>5},
 {"id"=>"SUBMCD", "type"=>"Text", "len"=>5},
 {"id"=>"SUBMCDCC", "type"=>"Text", "len"=>2},
 {"id"=>"SDELM", "type"=>"Text", "len"=>5},
 {"id"=>"SDSEC", "type"=>"Text", "len"=>5},
 {"id"=>"SDUNI", "type"=>"Text", "len"=>5},
 {"id"=>"AREALAND", "type"=>"Text", "len"=>14},
 {"id"=>"AREAWATR", "type"=>"Text", "len"=>14},
 {"id"=>"NAME", "type"=>"Text", "len"=>90},
 {"id"=>"FUNCSTAT", "type"=>"Text", "len"=>1},
 {"id"=>"GCUNI", "type"=>"Text", "len"=>1},
 {"id"=>"POP100", "type"=>"Text", "len"=>9},
 {"id"=>"HU100", "type"=>"Text", "len"=>9},
 {"id"=>"INTPTLAT", "type"=>"Float", "len"=>11},
 {"id"=>"INTPTLON", "type"=>"Float", "len"=>12},
 {"id"=>"LSADC", "type"=>"Text", "len"=>2},
 {"id"=>"PARTFLAG", "type"=>"Text", "len"=>1},
 {"id"=>"RESERVE3", "type"=>"Text", "len"=>6},
 {"id"=>"UGA", "type"=>"Text", "len"=>5},
 {"id"=>"STATENS", "type"=>"Text", "len"=>8},
 {"id"=>"COUNTYNS", "type"=>"Text", "len"=>8},
 {"id"=>"COUSUBNS", "type"=>"Text", "len"=>8},
 {"id"=>"PLACENS", "type"=>"Text", "len"=>8},
 {"id"=>"CONCITNS", "type"=>"Text", "len"=>8},
 {"id"=>"AIANHHNS", "type"=>"Text", "len"=>8},
 {"id"=>"AITSNS", "type"=>"Text", "len"=>8},
 {"id"=>"ANRCNS", "type"=>"Text", "len"=>8},
 {"id"=>"SUBMCDNS", "type"=>"Text", "len"=>8},
 {"id"=>"CD113", "type"=>"Text", "len"=>2},
 {"id"=>"CD114", "type"=>"Text", "len"=>2},
 {"id"=>"CD115", "type"=>"Text", "len"=>2},
 {"id"=>"SLDU2", "type"=>"Text", "len"=>3},
 {"id"=>"SLDU3", "type"=>"Text", "len"=>3},
 {"id"=>"SLDU4", "type"=>"Text", "len"=>3},
 {"id"=>"SLDL2", "type"=>"Text", "len"=>3},
 {"id"=>"SLDL3", "type"=>"Text", "len"=>3},
 {"id"=>"SLDL4", "type"=>"Text", "len"=>3},
 {"id"=>"AIANHHSC", "type"=>"Text", "len"=>2},
 {"id"=>"CSASC", "type"=>"Text", "len"=>2},
 {"id"=>"CNECTASC", "type"=>"Text", "len"=>2},
 {"id"=>"MEMI", "type"=>"Text", "len"=>1},
 {"id"=>"NMEMI", "type"=>"Text", "len"=>1},
 {"id"=>"PUMA", "type"=>"Text", "len"=>5},
 {"id"=>"RESERVED", "type"=>"Text", "len"=>18}]

num_format='9'*11+'.'+'9'*11
pos=1;
substring_part=columns.map do |x|
	l = x['len'];
	r = "substring(data,#{pos},#{l})"
	r = "to_number(#{r},'#{num_format}')" if x['type']=="Float"
	r = "trim(#{r})" if x['type']=="Text"
	r +=" as #{x['id']}";
	pos+=l;
	r 
end*", "

insert_part = columns.map{|x| "\"#{x["id"]}\""}*", "

table_name = "census"
stage_name = "geo_staging"

File.open("insert_geo_to_final.sql","w") {|f| f<< "INSERT INTO #{table_name}(#{insert_part}) SELECT #{substring_part} FROM #{stage_name};"}